services:
  tor:
    build: ./tor
    #image: ghcr.io/joshhighet/multisocks/tor:latest
    networks:
      - net_tor
    expose:
      - 9050
      - 9051
    deploy:
      replicas: ${SOCKS:-5}
    restart: always

  metrics:
    build: ./metrics
    networks:
      - net_tor
    ports:
      - "8000:8000"
    depends_on:
      - tor
    expose:
      - 8000
    deploy:
      replicas: 1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  haproxy:
    build: ./haproxy
    restart: always
    depends_on:
      tor:
        condition: service_started
      haconfig-generator:
        condition: service_completed_successfully
    ports:
      - 8080:8080
      - 1337:1337
    volumes:
      - haproxy_conf:/usr/local/etc/haproxy
      - ./haproxy/check-tor.sh:/usr/local/etc/haproxy/check-tor.sh
    networks:
      - net_tor
    
  haconfig-generator:
    build: ./haconfig
    command: python gen_conf.py
    depends_on:
      tor:
        condition: service_started
    volumes:
      - haproxy_conf:/usr/local/etc/haproxy
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - net_tor

volumes:
  haproxy_conf:

networks:
  net_tor:
    name: net_tor
