# build
FROM node:20-alpine AS builder
LABEL org.opencontainers.image.source https://github.com/joshhighet/multisocks/metrics
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# host
FROM node:20-alpine AS production
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nextjs -u 1001
RUN chown -R nextjs:nodejs /app
USER nextjs
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]