FROM python
LABEL org.opencontainers.image.source https://github.com/joshhighet/multisocks/haconfig
WORKDIR /usr/app/
RUN pip install docker jinja2
COPY haproxy.j2 /usr/app/haproxy.j2
COPY gen_conf.py /usr/app/gen_conf.py
